title: psichomics
description: Interactive R package to quantify, analyse and visualise alternative splicing data from The Cancer Genome Atlas (TCGA) or the Genotype-Tissue Expression (GTEx).
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
